### ISSUE TITLE
Support for JRuby > 1.9.3

### ISSUE THREAD

**Issue by sshaw** [sshaw/jaxb2ruby#6]
This looks to be the only problem:

```
JAXB2Ruby::Template::a class created by the ruby template#test_0003_has singular read/write accessors for attributes:
ArgumentError: wrong number of arguments (1 for 0)
    /Users/sshaw/code/ruby/jaxb2ruby/jaxb2ruby/lib/jaxb2ruby/converter.rb:75:in `find_namespace'
    /Users/sshaw/code/ruby/jaxb2ruby/jaxb2ruby/lib/jaxb2ruby/converter.rb:93:in `translate_type'
    /Users/sshaw/code/ruby/jaxb2ruby/jaxb2ruby/lib/jaxb2ruby/converter.rb:135:in `extract_class'
    /Users/sshaw/code/ruby/jaxb2ruby/jaxb2ruby/lib/jaxb2ruby/converter.rb:233:in `block in extract_classes'
    org/jruby/RubyArray.java:1733:in `each'
    /Users/sshaw/code/ruby/jaxb2ruby/jaxb2ruby/lib/jaxb2ruby/converter.rb:230:in `extract_classes'
    /Users/sshaw/code/ruby/jaxb2ruby/jaxb2ruby/lib/jaxb2ruby/converter.rb:42:in `create_ruby_classes'
    /Users/sshaw/code/ruby/jaxb2ruby/jaxb2ruby/lib/jaxb2ruby/converter.rb:29:in `convert'
    /Users/sshaw/code/ruby/jaxb2ruby/jaxb2ruby/lib/jaxb2ruby/converter.rb:14:in `convert'
    /Users/sshaw/code/ruby/jaxb2ruby/spec/spec_helper.rb:10:in `convert'
    /Users/sshaw/code/ruby/jaxb2ruby/spec/template_spec.rb:68:in `block in (root)'
    org/jruby/RubyBasicObject.java:1687:in `instance_eval'
```

**Comment by sshaw** [comment]
This is fixed on the modern-java-branch. As of this comment, it's not released.
